### ISSUE TITLE
Add docker compose

### ISSUE THREAD

**Issue by XaoGao** [joemasilotti/railsdevs.com#260]
Hi, i think it would be better to add docker-compose because to deploy the server locally, you need to install postgresql, i can do it if you wanna

**Comment by joemasilotti** [comment]
Personally, I'm not inclined to add Docker to this project. I don't use it day-to-day and don't want to take on the maintenance responsibility. But if you create an image I can link to it from the README.

**Comment by alexferrari88** [comment]
@XaoGao did you have any success in creating a docker-compose file?

**Comment by JefvdA** [comment]
Hi there, I wanted to contribute to this project, but I'm not really a fan of installing software directly on my device and almost always lean into using Docker. Any plans on still adding Docker to this project? And if not would it be ok for me to add Docker support?

**Comment by JefvdA** [comment]
> > Personally, I'm not inclined to add Docker to this project. I don't use it day-to-day and don't want to take on the maintenance responsibility. But if you create an image I can link to it from the README.

You were only talking about an `image`, but I don't think that would be enough for this project. A `docker-compose` and `Dockerfile' file would sure be easier, maybe even necessary because of all the dependencies, but if it's something you don't want to add because of extra maintenance that sure is understandable.
