### ISSUE TITLE
Redesign filters on `/developers`

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#356]
The filters on `/developers` are becoming a bit cumbersome. I'd like to redesign the page to look like [this Tailwind UI component](https://tailwindui.com/components/ecommerce/components/category-filters#component-e799517f86cc2fc79bf0eebb45c16eea). Apologies for the janky image, but I think this gets across the idea well enough. Down the left is Search, Work preference, Role level, followed by Timezone. Sort remains on the right.

![image](https://user-images.githubusercontent.com/2092156/161160009-e56ae5a2-b0c5-400c-9a0b-095c1bf3efae.png)

PR #348 has some thoughts and the beginning of code for this. A PR addressing this issue should:

- [ ] Redesign `/developers` to match the Tailwind UI design linked above
    - [ ] Desktop and mobile
- [ ] Continue to show/hide inputs based on the matching `Feature` flag
- [ ] Add a button to submit the entire form
    - [ ] Ensure this button never scrolls off the bottom of the page
- [ ] Add a clear button to clear/reset the entire form (visit `/developers`) to the left of the submit button
- [ ] **BONUS**: Abstract the form rendering in a way that would make it easy to add new fields in the future

Please do _not_ attempt to bring in Hotwire in this PR. That can come later!

**Comment by adrianvalenz** [comment]
This sounds fun. I’m up for it!

**Comment by joemasilotti** [comment]
Awesome, all yours @adrianvalenz! I imagine there will be a lot of back and forth on this, so feel free to share progress and ask questions if you have any during your work.

Thanks for tackling this 💪

**Comment by adrianvalenz** [comment]
@joemasilotti Sounds good! I'm excited to help out!

**Comment by joemasilotti** [comment]
Hey @adrianvalenz, I was wondering if you have any progress updates on this? It's been over a week and I want to make sure you still have the appetite to get this working. If not, no worries! Let me know and I can pass it on to someone else.

**Comment by adrianvalenz** [comment]
Hey Joe!

I’ve made a little progress on it. I was looking at how the sort dropdown filter was on the other side of the design where as the rest of the form was on the left sidebar, one of the things I’m implementing right now is the use of form attribute. An input field can be outside of the <form> tags but as long as you point the input field to the form via the attribute it can be on a separate div container all together. I was going to message you soon actually and was wondering if that is something you had considered, otherwise I think it would work. I also have an idea on abstracting the design to add more fields in the future. But yes I’m really excited about it and will still like to continue playing with it. If you are operating under a set deadline I’d be more than happy to make sure I meet it! 

Adrian.

**Comment by adrianvalenz** [comment]
I’ll be pushing up a WIP PR soon to get some feedback I just want to have something solid! Which I believe I will!

I must admit I had not seen your tweet! It was just something I deduced initially when I was looking over the project. I had learned about the form attribute a while back. 

I did see your tweet or response about MiniTest vs RSpec (I know it’s is little off topic) but I would love to chat more about it since it is an interest of mine. I really love how MiniTest is just Ruby and it makes you a better Rubyist. And while I do appreciate RSpec for its own reasons I don’t understand why it’s preferred at an overwhelming rate over MiniTest in enterprise or corporate settings. And close 50/50 balance would make more sense to me but I know RSpec came out with a book and better documentation early on, which really helps adoption. But MiniTest parallel testing built in and other goodies…it’s like coke on guys. Lol.

Anyway! I digress. Thank you again for your patience!

Adrian

**Comment by joemasilotti** [comment]
> I’ll be pushing up a WIP PR soon to get some feedback I just want to have something solid! Which I believe I will!

Sounds great – looking forward to it!

> I did see your tweet or response about MiniTest vs RSpec (I know it’s is little off topic) but I would love to chat more about it since it is an interest of mine...

Sure thing! I started with RSpec/FactoryBot, too. Feel free to open a Discussion on the project. Also, DMs are open on Twitter if prefer to talk more privately.

**Comment by adrianvalenz** [comment]
Hey Joe!

Good morning! Hope this email finds you well! I was getting ready to make some updates and I couldn’t interact with the repo. I was a bit confused as I couldn’t find Issue #356

Regards,
Adrian

**Comment by joemasilotti** [comment]
Hey Adrian, that's awesome to hear! I'm looking forward to seeing what you've built.

That's weird – _this_ is #356. Did you mean #348? I can access both (in private browsing). I'm thinking it's a GitHub issue? Can you try again and let me know what's going on?

**Comment by adrianvalenz** [comment]
Yes, thank you! I’ll try again.

**Comment by joemasilotti** [comment]
Hey @adrianvalenz, were you able to interact with the repo?

**Comment by joemasilotti** [comment]
Hey again @adrianvalenz, I'd love for work to start on this and we are coming up on a month since you originally claimed it. Can you let me know if you still have appetite to knock this out? If not, no worries and I can take a pass.

**Comment by adrianvalenz** [comment]
https://github.com/joemasilotti/railsdevs.com/compare/main...adrianvalenz:feature/redesign-developer-filters?expand=1

This is what I just pushed up. I got the sort filter working in a different component so you can style it a bit easier now. They are linked via the form attribute. Needed to add a "form" parameter for initialization and some translation key words...it's not the end product because it is still a little sloppy, but it is working!

**Comment by joemasilotti** [comment]
Exciting! Can you please create a PR out of that and mark it as a draft? Then we can move our conversation over there by commenting on the code directly.

**Comment by joemasilotti** [comment]
Closed via #409.

**Comment by adrianvalenz** [comment]
Hey Joe!

Yes I was able to sort it out! User error mostly! Lol

Adrian

>
