### ISSUE TITLE
MessagingTest#test_sending_a_message_via_a_Turbo_Stream randomly fails

### ISSUE THREAD

**Issue by metamoni** [joemasilotti/railsdevs.com#437]
**Describe the bug**
I think there's a flaky test floating around. I've seen this error when running `bin/check` three times now. If I rerun it, it eventually passes.

```
Failure:
MessagingTest#test_sending_a_message_via_a_Turbo_Stream [/Users/monicamateiu/repos/railsdevs.com/test/system/messaging_test.rb:11]
Minitest::Assertion: expected to find text "Hello!" in "railsdevs\nDevelopers\nPricing\nAbout\nView conversations\nView notifications\nYou have a new notification\nOpen user menu\nConversation\nwith\nProspect Developer\nFlag this conversation\nYou wrote\n1 day ago\nEarlier message.\nYou wrote\nless than a minute ago\nOne message.\nProspect Developer wrote\nless than a minute ago\nTwo message.\nAdd your message\n⌘\n+ Enter\nSending...\nEnglish\nEspañol\n繁體中文\nPortuguês (Brasil)\nAbout\nSupport\nOpen source\nOpen startup\nAnalytics\nTwitter\nGitHub\nEmail\n© 2022 Masilotti.com. All rights reserved.". (However, it was found 1 time including non-visible text.)

413 tests, 926 assertions, 1 failures, 0 errors, 0 skips
```

**To Reproduce**
1. Run `bin/check` until you see the error
2. Run `bin/check` again without making any changes, until the error disappears

**Expected behavior**
All tests should always pass

**Screenshots**
![Screenshot 2022-05-21 at 14 45 49](https://user-images.githubusercontent.com/22390758/169654785-4b888467-4d2b-440c-9ba0-563102178fea.png)

**Comment by joemasilotti** [comment]
Can you share the linked screenshot? I haven't seen this test fail before but definitely want to fix it since it's flaky.

**Comment by metamoni** [comment]
![failures_test_sending_a_message_via_a_Turbo_Stream](https://user-images.githubusercontent.com/22390758/169657218-4212e607-c486-4cdb-a800-1911aafad51d.png)

**Comment by joemasilotti** [comment]
Weird, the text _is_ showing up in the screenshot! This line in the error message is even weirder:

> (However, it was found 1 time including non-visible text.)

We are trying to find it one time, no? I don't understand why this would be failing.

The text in your error message being "read" doesn't include "Hello!" which almost seems like the text is hidden. Which is bizarre.

---

Can you try the following? Add `binding.pry` to `test/system/messaging_test.rb:10` and run `HEADFUL=1 rails test test/system/messaging_test.rb`. This should pause test execution right before the failing assertion with a visible browser.

Then you should be able to check if the text is correctly on the screen and inspect it to see if it is somehow hidden.

Type `exit` in the console to continue execution of the test.

**Comment by metamoni** [comment]
Trying to debug this but it seems to be passing whenever I run that test file on its own, or when I run all system specs with `HEADFUL=1 rails test:system` or `bundle exec rails test:all` and put in `binding.pry`. It's all very weird, because as soon as I remove the breakpoint I get failures again. So I'm afraid that didn't help me get anything useful 😕

**Comment by jayeclark** [comment]
Could it be a race condition? The ‘sending’ in the error message makes me think that sometimes the message is still in the process of being sent when the test is reading the page content. (If a ‘Sending’ status message exists, then it seems likely that the conversation can be in ‘Sending’ state for a non trivial amount of time…)

`Click_button` simply clicks the button, it doesn’t wait for a form to post. So the test is clicking the button and then `assert_text` is immediately looking for ‘Hello’ to be on the page. One of three things could be true depending on how soon `assert_text` reads the page content:  1. Hello could be present in the form input text area (my guess is this is the state that the test is sometimes reading, maybe it considers input values as ‘hidden’ text?), 2. Hello could not be present at all because the form data has reset but the new message hasn’t been rendered by the Turbo Stream yet, or 3) Hello could be present in the rendered message.

It might be an issue of only a few milliseconds, which could explain why a subsequent screenshot shows the text in question in message form and seems to contradict the test result...and also why running the test on its own, without other competing requests to create potential threading issues that could exacerbate the timing issue, yields the expected ‘pass’ result.

**Comment by joemasilotti** [comment]
Ah! Great thinking @jayeclark. The "Sending" copy does seem to indicate the message was never sent. 

I don't remember off the top of my head, but I thought Capybara waited for elements. Maybe we aren't using the right method though.

**Comment by joemasilotti** [comment]
@metamoni, can you please try #439 and see if that fixes the race condition?

**Comment by metamoni** [comment]
@jayeclark excellent detective work! I ran the tests a bunch of times on your branch and it all seems to be working fine now, @joemasilotti.

**Comment by joemasilotti** [comment]
Amazing! High five for teamwork! 🙌

**Comment by jayeclark** [comment]
🙌  Woo boo, glad to help! 🙌
