### ISSUE TITLE
Invisibilize for businesses

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#500]
There has been a tiny uptick in spam-ish requests in the past few days. Similar to how we can "invisibilize" developers, I'd like to do the same for businesses.

## A PR addressing this issue should:

- [ ] Add a column to `Business` to mark if it is visible
- [ ] 404 if a business's show page is visited but that business is set to invisible
- [ ] Show a native confirm dialog before proceeding
- [ ] Add a button for admins to "Invisibilize" a business and send an email

A lot of the last to-do can use #367 as a reference.

**Comment by joemasilotti** [comment]
@DRBragg, you have first dibs if you want this one!

**Comment by DRBragg** [comment]
> @DRBragg, you have first dibs if you want this one!

Awesome! I'll knock it out this weekend. Thanks!

**Comment by joemasilotti** [comment]
Excellent! Thank you. 

A heads up to log in as `admin@example.com` locally. There is already a bit of subscription info there in the business pages.

**Comment by DRBragg** [comment]
Hey Joe.  Just wanted to confirm the wording on the email:

Hey #{business.name},

I'm Joe, the founder of railsdevs. Your business profile (link to business profile) was flagged because it doesn't contain enough information and kind of looks like spam.

I've set your profile to invisible. No one but yourself will be able to see it. You can toggle this back when you flesh out your profile a bit more.

Thanks,
Joe

**Comment by joemasilotti** [comment]
Yeah, looks good to me! The closing can be replaced with the signature partial, too.
