### ISSUE TITLE
Link to conversations from developer and business pages

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#602]
A PR addressing this issue should:

1. Add a new link to the Admin section of business and developer profiles
2. Link to `admin_developer_conversations_path` or `admin_business_conversations_path`

Design-wise, there will be more links added to this section. So creating a new "pill" of three buttons could work. Or, redesigning the buttons altogether to allow for more.

If you don't want to do any design no worries – submit a PR unstyled and I can take it from there!

**Comment by fk00750** [comment]
Hey @joemasilotti can you assign me this issue ?

**Comment by joemasilotti** [comment]
Sure thing – all yours!

**Comment by joemasilotti** [comment]
Hey @fk00750, I haven't seen any updates in almost a month. Do you still have appetite to work on this? If not, no worries! I can assign it to someone else.

**Comment by xmarlox** [comment]
@joemasilotti i'm interested working on this 
but i don't quite get what you mentioned _"Admin section of business and developer profiles"_ 
is it the highlighted section from [this screenshot](https://drive.google.com/file/d/1si1DHR9WF25Egyb8-KiRTo4uIzXrNB75/view?usp=sharing) ?

also for the pill buttons, will [this](https://postsrc.com/components/buttons/pill-buttons) suffice? if yes, then which one? otherwise, you can guide me on what you have in mind.

thanks!

**Comment by joemasilotti** [comment]
The admin section is highlighted in this screenshot.

![image](https://user-images.githubusercontent.com/2092156/191768064-913b8d26-5252-496d-b91d-3ea24170f4c5.png)

Feel free to copy the existing design of three pills into a new row/section of pills with a single button for this link.

**Comment by xmarlox** [comment]
@joemasilotti ✋🏽 
here's the [PR to address this issue](https://github.com/joemasilotti/railsdevs.com/pull/676) 😃

**Comment by sarvaiyanidhi** [comment]
Hi @joemasilotti Looks like this issue is open now.. Can I take it up?

**Comment by joemasilotti** [comment]
Yes please! All yours, @sarvaiyanidhi.

**Comment by joemasilotti** [comment]
Closed via #755.
