### ISSUE TITLE
LinkedIn API integration

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#756]
I'm exploring another way to keep businesses honest and pay the required hiring fee. One idea is to track developers on LinkedIn and see if their job status changes.

I'm not yet looking for deployable code. This is more of a research and development issue. But I'd love to know what I can do with the LinkedIn API.

In an ideal world admins would receive an email notification when a developer on RailsDevs changed their employer on LinkedIn. Some folks already have a link to their LinkedIn profile, so we can ideally use that.

Another possibility is coming at it from the other angle. When a business becomes a subscriber see who works for them according to LinkedIn. Periodically update this and if anyone matches a Ruby or Rails developer then send a notification to admins on RailsDevs.

Is this possible with the LinkedIn API? Is there a cost associated?

A POC or even a quick write up would be great!

**Comment by BenteGber** [comment]
I'll snag this one

**Comment by joemasilotti** [comment]
All yours! Thanks :)

**Comment by joemasilotti** [comment]
Feel free to drop your findings here or start a new Discussion, whatever works best for your writing style.

**Comment by BenteGber** [comment]
# Tracking Candidate Hiring with 3rd party API’s 
## Goal 
Tracking candidate job status changes on LinkedIn, Github, and other platforms. 

### LinkedIn

So Linked In does not appear to have an API that really fits this purpose.  The closest I could find is the Recruiter System Connect and it is more catered towards integrations with existing Applicant Tracking Systems or migrations from those systems into LinkedIn’s [Talent Hub](https://business.linkedin.com/talent-solutions/talent-hub?trk=bl-po_what-is-an-applicant-tracking-system).

Here are some links if someone wants to dig a little deeper.
[Module 3](https://learn.microsoft.com/en-us/linkedin/talent/recruiter-system-connect/retrieve-exported-candidates) of the API guide was the most relevant I could find
[Linked In API RSC](https://learn.microsoft.com/en-us/linkedin/talent/recruiter-system-connect): Overview of the RSC API
[GitHub Repo](https://github.com/linkedin-developers/recruiter-system-connect-development-tools) 

It also appears that they require submission and review before creating any integrations with that API
[Development Prerequisites](https://learn.microsoft.com/en-us/linkedin/talent/recruiter-system-connect#1-development-prerequisites)

There is what appears to be a simpler endpoint that allows you to track individual job postings on Linked In but I don’t feel that it accurately meets the needs described in the issue.
[Check Job Posting Status API](https://learn.microsoft.com/en-us/linkedin/talent/job-postings/api/check-job-posting-status)

Tried to  get in and tinker with the API itself but as mentioned it looks like you must specifically enroll in the Partner Program to use those API’s. [Reference](https://learn.microsoft.com/en-us/linkedin/shared/authentication/getting-access)

[Quote from SO](https://stackoverflow.com/questions/50626514/linkedin-this-application-is-not-allowed-to-create-application-tokens): 
Two legged auth is not available for any use case where member data is retrieved. All calls for member data must be three legged. Documentation exists because there are rare use cases where two legged auth can be used, but that partner program is not open at this time. To retrieve information about an organization, you will need to have a member that is listed as an admin for that specific company page. Permissions to access company page data are included in the Marketing Developer Program. Apply to the program at  [linkedin.com/developers](https://www.linkedin.com/developers/) 


## GitHub 
Incredibly simple 

`GET https://api.github.com/users/{username}`

Returns a flat JSON object with the top level key of  `"company"`

Without auth there is rate limiting 60/hr with no account or 5000 if you authorize with user credentials.

## Others
Didn’t dig very deep but here are a couple worth mentioning 

### Xing 
Very popular in Europe and Looks like they have an [Official Ruby Client](https://github.com/xing/xing_api) which is nice

### Twitter…?
They definitely have a simple API that would work for it but who knows what the future holds in the Kingdom of Elon.

**Comment by joemasilotti** [comment]
Thanks for this, @BenteGber! It seems like LinkedIn really has their API too locked down to do anything meaningful for RailsDevs. But I am curious about the a potential GitHub integration.

I'm going to close this and create a new issue for that. Thank you again!
